### ISSUE TITLE
TypeError: Cannot read property 'prev' of undefined

### ISSUE THREAD

**Issue by justmoon** [interledgerjs/ilp-routing#18]
```
mark 2016-12-10T03:25:18.621Z connector:app error TypeError: Cannot read property 'prev' of undefined
mark     at eliminate (/opt/workspace/interledgerjs/five-bells-demo/node_modules/code42day-vis-why/index.js:65:28)
mark     at simplify (/opt/workspace/interledgerjs/five-bells-demo/node_modules/code42day-vis-why/index.js:125:3)
mark     at LiquidityCurve.simplify (/opt/workspace/interledgerjs/five-bells-demo/node_modules/ilp-routing/src/lib/liquidity-curve.js:55:31)
mark     at Route.simplify (/opt/workspace/interledgerjs/five-bells-demo/node_modules/ilp-routing/src/lib/route.js:94:33)
mark     at combineRoutesByConnector (/opt/workspace/interledgerjs/five-bells-demo/node_modules/ilp-routing/src/lib/routing-tables.js:260:21)
mark     at table.destinations.each (/opt/workspace/interledgerjs/five-bells-demo/node_modules/ilp-routing/src/lib/routing-tables.js:139:31)
mark     at PrefixMap.each (/opt/workspace/interledgerjs/five-bells-demo/node_modules/ilp-routing/src/lib/prefix-map.js:45:7)
mark     at eachSource (/opt/workspace/interledgerjs/five-bells-demo/node_modules/ilp-routing/src/lib/routing-tables.js:138:26)
mark     at PrefixMap.each (/opt/workspace/interledgerjs/five-bells-demo/node_modules/ilp-routing/src/lib/prefix-map.js:45:7)
mark     at RoutingTables.eachSource (/opt/workspace/interledgerjs/five-bells-demo/node_modules/ilp-routing/src/lib/routing-tables.js:115:34)
mark     at RoutingTables.toJSON (/opt/workspace/interledgerjs/five-bells-demo/node_modules/ilp-routing/src/lib/routing-tables.js:137:10)
mark     at RoutingTables.toJSON (/opt/workspace/interledgerjs/five-bells-demo/node_modules/ilp-connector/src/lib/routing-tables.js:81:30)
mark     at RouteBroadcaster.broadcast (/opt/workspace/interledgerjs/five-bells-demo/node_modules/ilp-connector/src/lib/route-broadcaster.js:69:39)
mark     at RouteBroadcaster.start (/opt/workspace/interledgerjs/five-bells-demo/node_modules/ilp-connector/src/lib/route-broadcaster.js:50:12)
mark     at start.next (<anonymous>)
mark     at onFulfilled (/opt/workspace/interledgerjs/five-bells-demo/node_modules/co/index.js:65:19)
```

**Comment by sentientwaffle** [comment]
Any additional context for this? I can see that its from within the demo, but was there any custom configuration or anything? I just ran the latest version of the demo without any issues.

**Comment by michielbdejong** [comment]
This error happened in a version long before the current one, please reopen if this can still be reproduced.
